### PR TITLE
Update front page and include D3 vis there

### PR DESCRIPTION
**Pull request by karawoo**
I've updated the text on the front page to be a little friendlier and talk about the motivations for the project. I moved the D3 visualization to the front page (away from the Data Gathering page).

### CODE REVIEW

**Comment by valentina-s** [comment]
I liked how the previous intro had the two points: one for mining, one for integration of data. Do you think it would be good to add something like that?

Also maybe at least for the first paragraph instead of past tense, use present tense. I am thinking in terms of writing papers: people usually have done the work in the past, in the abstract they use present tense.

**Comment by karawoo** [comment]
I like both of these suggestions. I'll make the changes (but probably not before our practice presentations, if that's ok -- I'm practicing my parts of the talk in my head)

**Comment by karawoo** [comment]
@valentina-s I updated the text, let me know what you think.

**Comment by valentina-s** [comment]
Thanks, looks good! Can you just make say 'preliminary classification models', ie plural: many makes it more intriguing ;)

**Comment by karawoo** [comment]
Done :)

**Pull request merged**
