### PR TITLE
update processed enforcement data to match format of processed press data

### PR DESCRIPTION
**Pull request by mikiverma**

### CODE REVIEW

**Comment by karawoo** [comment]
It looks like this is also changing the data preprocessing code, yeah? Does this make `data_preprocess.py` redundant? If so maybe we should remove `data_preprocess.py` and update other code that depends on it to reduce duplication and possible confusion.

**Comment by mikiverma** [comment]
Yes the last pull request was meant only to go to my fork because it is not finished, but I didn't realize that the other pull request was still open. The original `data_preprocess.py` should be deleted, but since we haven't decided exactly how to split up the modules, those names are not final, so I was going to hold off. Is there other code apart from mine that uses functions in the `data_preprocess.py`?

**Comment by karawoo** [comment]
I'm not sure if any other code depends on it or not, just wanted to make sure we're not inadvertently breaking other things. But it sounds like probably not.

**Comment by valentina-s** [comment]
Merging this PR since it is mainly adding new code. Before deleting data_preprocess.py, we will have to check if it is not a dependency.

**Pull request merged**
