### PR TITLE
Updated Preliminary Classification Page

### PR DESCRIPTION
**Pull request by cvint13**
The r code and csv are artifacts from my visualizations and summary statistics included in the page.

### CODE REVIEW

**Comment by cvint13** [comment]
let me know if you want me to resolve the issues with the merge, i didn't want to do that until you decided that the page looked good.

**Comment by valentina-s** [comment]
Thanks, Cynthia!

Overall looks good! Could you add some links to the full Jupyter notebooks/code on github?

A few other minor comments:
- When discussing which algorithms were used, instead of the word 'try' I think it is better to use the word test (or studied the performance). (After all you run all the classifiers, did not simply try running them ;)). Also maybe remove some of the repetition: 
  'We tested a logistic regression model with both L1 and L2 penalization.' 
- 'L1 handles irrelevant features that increase exponentially (the sample size need to grow logarithmicly with the features, so the features can grow exponentially: that is why L1 works better when there are many many features)
- Can you include in the table the word 'Regression'  - L1, L2 Regression, Ridge Regression
- Also maybe for SVC - SVM (Support Vector Machine) - that abbreviation is more popular so I don't think we need to explain it. We can put the acronym in the text in parentheses.
- There is a third empty column for the Most Predictive Terms table?
- For the ROC plot there is actually a new plot that Mike made just before leaving: it was using all the words and the average performance is about 65%!!!!! It was sent out in the slack channel. So I think we can claim that we have an improvement over random guessing  :) 
- I think in the Future Directions section you can substitute the first sentence (sounded a bit too pessimistic ;)) with something like: there is still wide margin for improvement and we need custom designed algorithms to extract the right features. Maybe after merging this we can create back the 'Future Directions' web page and expand on it. We can include the FDA topics and I can provide more references to the methods we have looked at.

**Comment by cvint13** [comment]
working on this right now....finally!!!

**Comment by cvint13** [comment]
did i fix everything in the page?

**Comment by valentina-s** [comment]
Yes, thanks! Just a typo in the word growth (griwth) in the initial paragraph.
Now looking at the text I see we cannot just substitute the old ROC curve with the new one (as the new one uses all words and the old one only the one mentioned above). So maybe it is best if we still keep the old one plot (with the 50% rate) and then adding the new one, stating that using all words improved the performance to .65.  We can double check with @mikemunsell to make sure this is the correct interpretation.

**Comment by mikemunsell** [comment]
Hi!  Just made it back to Boston so I'm finally getting to this.

Yes - that is the correct interpretation.  The model that performed with 50% accuracy only used the 'generic' food-borne illness terms (e.g., rancid, vomit, sick, etc.).  Using all words from the text in the model increased the accuracy to 65% (even with product-specific cross-validation), however, this model is not ideal since the model is not very generalizable.  Let me know if you have any other questions.

**Comment by valentina-s** [comment]
Welcome to east coast @mikemunsell!  By product specific-cross validation do you mean: ensuring testing on unseen products, or something else? I also suspect with the generic words a lot of words were not present at all in the reviews so without any features, the algorithm was simply guessing.

**Comment by mikemunsell** [comment]
Yes @valentina-s, by product specific-cross validation I mean that for each CV, the testing and training sets contained different ASINS.  I believe the full matrix had around 10,000 terms, so the algorithm was most likely guessing since most reviews would be represented by a row of zeros.

**Comment by valentina-s** [comment]
@mikemunsell then it is good, it is at least a little bit generalizable :) 
@cvint13 I will look into the conflicts so that we can merge it.

**Pull request merged**
