### PR TITLE
updated shiny app

### PR DESCRIPTION
**Pull request by cvint13**
updated format, visualizations.

### CODE REVIEW

**Comment by cvint13** [comment]
commented out install packages section as well

**Comment by valentina-s** [comment]
Seems there are two themes here: one about updating the shiny app, the other one about reorganizing the python-sql scripts.

**Comment by cvint13** [comment]
how do you split a pull request

**Comment by cvint13** [comment]
working on splitting these up

**Comment by cvint13** [comment]
cant split

**Pull request merged**
